### ISSUE TITLE
Play Around

### ISSUE THREAD

**Issue by arnavs** [arnavs/binder-test#1]
@jlperla Here's a "minimal" `conda` setup with one notebook, `qeds`, `quantecon`, `pip`. In case you wanted to play around. 

Takes about 45-60s to launch, when I try? And the actual cells run quickly enough. So it looks promising as a release valve.

Edit: More like 20 at the office.

**Comment by arnavs** [comment]
Note that the `conda` is important, as you can also configure a mybinder using `pip` (which would probably be tighter). But if you want to let people do work, then I think this makes more sense.

**Comment by jlperla** [comment]
I ran it.  Took at least a minute for me.

I think the key is that we *don't* want them to be able to do work.  We want them to be able to barely run whatever is in the notebook, and nothing more.

Do you think it would be tighter with the sort of miniconda docker I talked about?  I would start by seeing what the overhead is for the miniconda one without any additional packages and a "2 + 3" notebook.  That might give us a lowerbound on the possible performance.
